created: 2026-10-10T17:34:45.441Z
updated: 2026-10-10T17:34:45.923Z
update_count: 3
last_field: concern
kind: nested-class
title: driver-onboarding
children:
  - application
  - document-links
  - document-store
  - document-upload
  - office-review
  - otp-sign-in
  - requirements
parentPath: []
