created: 2026-10-10T17:33:19.019Z
updated: 2026-10-10T17:33:19.418Z
update_count: 3
last_field: context
kind: nested-class
title: github-actions
children:
  - ci-workflow
  - demo-apk-workflow
  - load-workflow
  - nightly-workflow
  - phase-gates-workflow
  - release-workflow
parentPath: []
