created: 2026-10-10T17:31:20.570Z
updated: 2026-10-10T17:31:39.571Z
update_count: 2
last_field: diagram
kind: nested-class
title: infra-deploy
children:
  - backup
  - caddy-https
  - local-compose
  - observability-stack
  - oracle-deploy
  - web-images
parentPath: []
