created: 2026-10-10T17:34:05.953Z
updated: 2026-10-10T17:34:06.346Z
update_count: 3
last_field: constraint
kind: nested-class
title: taxi-rides
children:
  - accept-trip
  - expiry-sweep
  - online-presence
  - ride-request
  - taxi-quote
  - trip-end
parentPath: []
