include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/src/foundation/tokens.g.dart
    - build/**
linter:
  rules:
    prefer_const_constructors: true
    prefer_single_quotes: true
    require_trailing_commas: false
