created: 2026-10-10T17:31:23.802Z
updated: 2026-10-10T17:31:23.802Z
update_count: 1
last_field: description
kind: nested-class
title: dispatch-engine
children: []
parentPath:
  - bullmq-queues
  - dispatch-queue
