created: 2026-10-10T17:34:08.184Z
updated: 2026-10-10T17:34:08.184Z
update_count: 1
last_field: description
kind: nested-class
title: live-service
children: []
parentPath:
  - api
  - live-notifications
