created: 2026-10-10T17:28:39.286Z
updated: 2026-10-10T17:28:39.512Z
update_count: 2
last_field: diagram
kind: nested-class
title: driver-app
children:
  - app-shell
  - data
  - l10n
  - screens
parentPath: []
