created: 2026-10-10T17:33:28.644Z
updated: 2026-10-10T17:33:28.644Z
update_count: 1
last_field: description
kind: nested-class
title: dispatch-engine
children: []
parentPath:
  - api
  - dispatch-operations
