created: 2026-10-10T17:31:38.152Z
updated: 2026-10-10T17:31:38.152Z
update_count: 1
last_field: description
kind: nested-class
title: today-tab
children: []
parentPath:
  - driver-app-routes
  - tab-shell
