created: 2026-10-10T17:31:37.735Z
updated: 2026-10-10T17:31:37.968Z
update_count: 2
last_field: description
kind: nested-class
title: tab-shell
children:
  - earnings-tab
  - profile-tab
  - schedule-tab
  - today-tab
parentPath:
  - driver-app-routes
