created: 2026-10-10T17:30:40.389Z
updated: 2026-10-10T17:30:40.389Z
update_count: 1
last_field: description
kind: nested-class
title: welcome-screen
children: []
parentPath:
  - student-app-routes
  - onboarding
