created: 2026-10-10T17:31:11.810Z
updated: 2026-10-10T17:31:12.220Z
update_count: 3
last_field: constraint
kind: nested-class
title: live-location
children:
  - eta-calc
  - gps-ingest
  - live-gateway
  - live-hub
  - position-sampling
  - redis-live-keys
parentPath: []
