created: 2026-10-10T17:31:38.382Z
updated: 2026-10-10T17:31:38.382Z
update_count: 1
last_field: description
kind: nested-class
title: schedule-tab
children: []
parentPath:
  - driver-app-routes
  - tab-shell
