created: 2026-10-10T17:33:17.942Z
updated: 2026-10-10T17:33:17.942Z
update_count: 1
last_field: description
kind: nested-class
title: settlement-approval
children: []
parentPath:
  - settlement-reports
